nginx:
  image: nginx
  ports:
    - "80:80"
  links:
      - php:php
  volumes:
      - ./:/var/www/default:Z
      - ./docker-components/nginx/hosts:/etc/nginx/conf.d
      - ./docker-components/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
       MYSQL_DATABASE: corrector_db
       MYSQL_USER: corrector_user
       MYSQL_PASSWORD: corrector_pass
       MYSQL_ROOT_PASSWORD: password

phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6
    links:
      - mysql
    ports:
      - "8080:80"
    env_file:
      - variables.env

php:
  build: .
  links:
        - mysql
  ports:
    - "9000:9000"
  volumes:
    - ./:/var/www/default:Z